################################################################################
# theme setup
################################################################################
[dnb.theme]
slug = "dark-skies"
