################################################################################
# theme setup
################################################################################
[dnb.theme]
slug = "dark-skies"

# default color scheme (dark/light)
# this is ignored if `dnb.theme.switcher.enabled` is true. In that case the
# value of `dnb.theme.switcher.default` is used.
colorscheme = "dark"

# selected icon theme.
# can be one of the identifiers of the icons module OR
# `specific` to indicate use values of `icon` values as individual classes OR
# `partial` to indicate the inclusion of the value as cached partial
icontheme = "bootstrap"

[dnb.theme.switcher]
enabled = true   # boolean
default = "dark" # `dark`, `light` or any theme of `dnb.theme.switcher.themes`

[dnb.theme.backtotop]
enabled = true
icon = "chevron-double-up"
class = "widget--back-to-top"
top_id = "top"

[dnb.theme.jsbuild.options]
# options for the js.Build method
# see https://gohugo.io/hugo-pipes/js/
minify = false
format = "iife"
target = "es2020"
# [dnb.theme.jsbuild.options.externals]
# - "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
# - "node_modules/jquery/dist/jquery.min.js"
# [dnb.theme.jsbuild.options.inject]
# - "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
# - "node_modules/jquery/dist/jquery.min.js"
# [dnb.theme.jsbuild.options.params]
# api = "https://example.org/api"

################################################################################
# hooks setup
################################################################################
[dnb.hooks]
[[dnb.hooks.items.theme.head-post-css]]
file = "head-post-css"
cached = false

[dnb.head]
colorschemeOrder = "dark light"
